# dev env
server:
  port: 8090

# Thymeleaf view template config
# disable cache for dev
spring:
  thymeleaf:
    cache: false
# datasource
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
# message resource config
# if true use system local and false to use baseName (e.g. 'messages')
  messages:
      fallback-to-system-locale: false

# basic security
security:
  basic:
    enabled: false

logging:
  level:
    org: DEBUG
#    org.springframework.security: DEBUG

github:
  client:
    clientId: 7176fb3b3437f2246cfd
    clientSecret: 76ead68dc33dc41f6ec5388f02e31427da039ebe
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    authenticationScheme: query
    clientAuthenticationScheme: form
#    pre-established-redirect-uri: http://localhost:8090/login/github
#    registered-redirect-uri: http://localhost:8090/login/github
#    use-current-uri: false
  resource:
    userInfoUri: https://api.github.com/user