spring:
  datasource:
    url: jdbc:mysql://192.168.2.132:3306/oauth2?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
management:
  context_path: /admin

security:
  user:
    password: password2
  oauth2:
    resource:
      filter-order: 3
