server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.39:3306/oauth?useUnicode=true&characterEncoding=utf8
    username: oauth
    password: Oauth@123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
  user:
    password: password1